name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with sparse checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: 'hugo-site/public'  # specify the subdirectory to checkout
          sparse-checkout-cone-mode: false

      - name: Move subdirectory contents to root
        run: |
          shopt -s dotglob
          mv hugo-site/public/* .
          rm -rf subdir

      # Further steps like deploy, publish, build etc.


